#pragma once

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>

#include <string>
#include <cstdint>
#include <array>

#include "DeviceIdentity.h"

namespace MobileUnlock::Pairing {

// --- SAS PIN ---
// Cryptographically secure 6-digit numeric PIN (000000 – 999999)
// Generated by the PC side in response to PAIR_REQUEST
// Transmitted to the user via out-of-band display on both screens
// Never stored after pairing completes
// Never transmitted across the network as plaintext
constexpr int SAS_PIN_LENGTH = 6;
constexpr int SAS_MAX_ATTEMPTS = 3;
constexpr int SAS_EXPIRY_SECONDS = 60;  // PIN expires 60 seconds after generation

// Generates a cryptographically secure 6-digit numeric SAS PIN string
// Returns empty string on failure
std::string GenerateSasPin();

// Validates the provided PIN against the stored PIN in constant time (no early-exit)
// Returns true only if the PIN matches and has not expired and attempts < max
bool ValidateSasPin(const std::string& candidatePin, const std::string& storedPin,
                    FILETIME generatedAt, int attemptsSoFar);

// Returns true if the SAS PIN has expired relative to the system time
bool SasPinExpired(FILETIME generatedAt);

// Computes UNIX time from a FILETIME for logging (non-sensitive, does not log PIN value)
int64_t FileTimeToUnixMs(FILETIME ft);

// Sanitize a candidate PIN: only allow exactly 6 decimal digits
bool IsValidPinFormat(const std::string& pin);

} // namespace MobileUnlock::Pairing
